// GENERATED by Automation/scripts/sync-worker.mjs from Automation/remotion/. Edit it there, then run `pnpm sync:worker`.
/**
 * Captions, as shortshero draws them.
 *
 * The editor stores its own CaptionStyle shape (app/editor/[videoId]/
 * editor-utils.ts); the renderer draws the "short" shape that
 * lib/captionRender.ts reads. `toRenderStyle` is shortshero's
 * editorToShortCaptionStyle, and DEFAULT_CAPTION_STYLE is ShortComposition's
 * default, both copied so the preview and the worker agree.
 */
import type { CaptionRenderStyle } from "./captionRender";

export type RenderCaptionStyle = CaptionRenderStyle & {
  positionBottom?: number;
  wordsPerBatch?: number;
  layout?: "inline" | "stacked";
  disabled?: boolean;
};

export const DEFAULT_CAPTION_STYLE: RenderCaptionStyle = {
  fontSize: 84,
  color: "#FFFFFF",
  backgroundColor: "#000000",
  bgOpacity: 0,
  inactiveColor: "rgba(255,255,255,0.62)",
  inactiveBackgroundColor: "transparent",
  fontFamily: `"Inter", system-ui, -apple-system, sans-serif`,
  fontWeight: "900",
  textTransform: "none",
  outlineColor: "#000000",
  outlineWidth: 7,
  textShadow: "0 6px 18px rgba(0,0,0,0.45)",
  highlight: "color",
  activeScale: 1.12,
  letterSpacing: 0,
  borderRadius: 16,
  padding: "10px 22px",
  positionBottom: 18,
  wordsPerBatch: 3,
  layout: "inline",
};

type EditorCaptionStyle = Record<string, unknown>;
const pick = <T,>(v: unknown, fallback: T): T => (v === undefined || v === null ? fallback : (v as T));

/** Editor CaptionStyle → the renderer's shape (shortshero's editorToShortCaptionStyle). */
export function toRenderStyle(e: EditorCaptionStyle | null | undefined): RenderCaptionStyle {
  if (!e) return DEFAULT_CAPTION_STYLE;
  const d = DEFAULT_CAPTION_STYLE;
  return {
    ...d,
    fontSize: pick(e.fontSize, d.fontSize),
    fontFamily: pick(e.fontFamily, d.fontFamily),
    fontWeight: e.fontWeight !== undefined ? String(e.fontWeight) : d.fontWeight,
    textTransform: pick(e.textTransform, d.textTransform),
    color: pick(e.activeColor, d.color),
    backgroundColor: pick(e.captionBgColor, d.backgroundColor),
    bgOpacity: pick(e.captionBgOpacity, d.bgOpacity),
    inactiveColor: pick(e.inactiveColor, d.inactiveColor),
    inactiveBackgroundColor: "transparent",
    positionBottom: pick(e.positionBottom, d.positionBottom),
    wordsPerBatch: pick(e.wordsPerBatch, d.wordsPerBatch),
    layout: pick(e.layout, d.layout),
    disabled: pick(e.disabled, false),
    outlineColor: pick(e.outlineColor, d.outlineColor),
    outlineWidth: pick(e.outlineWidth, d.outlineWidth),
    textShadow: pick(e.textShadow, d.textShadow),
    highlight: pick(e.highlight, d.highlight),
    activeScale: pick(e.activeScale, d.activeScale),
    letterSpacing: pick(e.letterSpacing, d.letterSpacing),
    borderRadius: pick(e.borderRadius, d.borderRadius),
    padding: pick(e.padding, d.padding),
  };
}
