// GENERATED by Automation/scripts/sync-worker.mjs from Automation/remotion/. Edit it there, then run `pnpm sync:worker`.
import type { CSSProperties } from "react";
// Core `remotion` only (no @remotion/media): the worker runs remotion 4.0.459.
import { AbsoluteFill, Audio, Img, OffthreadVideo, Sequence, interpolate, spring, useCurrentFrame, useVideoConfig } from "remotion";
import { captionGroupStyle, captionWordStyle } from "./captionRender";
import { toRenderStyle } from "./captions";
import { FPS, LOGO_ANIMATIONS, SCHEMA_VERSION, bandBox, clipLayout, clipText, isLogoEffect, mainPieces, parseAccent, totalFrames, type Layout, type Piece, type PromoProps } from "./schema";

const clamp = { extrapolateLeft: "clamp", extrapolateRight: "clamp" } as const;

/**
 * Renders the shortshero editor's document in this app's layout: each
 * main-track clip in the band with its text above, overlay tracks on top
 * (shortshero's ExtraClipLayer), word captions (shortshero's captionRender),
 * music from its best part, and a fade to black on the last clip.
 */
export function PromoVideo(props: PromoProps) {
  if (props.schemaVersion !== SCHEMA_VERSION) {
    throw new Error(`Props schemaVersion ${props.schemaVersion} does not match composition version ${SCHEMA_VERSION}. Run \`pnpm sync:worker\` in Automation and redeploy render-hetzner.`);
  }
  const { width, height } = useVideoConfig();
  const frame = useCurrentFrame();
  const pieces = mainPieces(props);
  const total = totalFrames(props);
  // An animated logo card dims itself (to half, like the reference videos), so it skips the fade to black.
  const lastIsLogoCard = pieces.length > 0 && isLogoEffect(props.imageEffects[pieces.length - 1]);
  const fade = props.layout.fadeOutEnd && pieces.length && !lastIsLogoCard ? interpolate(frame, [total - 18, total], [0, 0.75], clamp) : 0;

  return (
    <AbsoluteFill style={{ backgroundColor: props.layout.bgColor }}>
      {pieces.map((piece) => (
        <Sequence key={`main-${piece.index}`} from={piece.from} durationInFrames={piece.durF} name={`Clip ${piece.index + 1}`}>
          <MainPiece props={props} piece={piece} width={width} height={height} />
        </Sequence>
      ))}
      {[...props.extraTracks].reverse().map((track) =>
        track.visible !== false
          ? track.clips.map((clip) => (
              <Sequence key={clip.id} from={Math.round(clip.startFrame ?? 0)} durationInFrames={Math.max(1, Math.round(clip.durationFrames ?? 30))}>
                {clip.type === "text" ? (
                  clip.hidden ? null : <TextClipLayer text={clip.text ?? ""} layout={withTextColor(clip.role === "cta" ? ctaLayout(props, pieces, clip.startFrame ?? 0) : props.layout, clip.textColor)} width={width} height={height} y={clip.textY} bg={clip.textBg ? withAlpha(clip.textBg, clip.textBgOpacity ?? 1) : undefined} />
                ) : (
                  <ExtraClipLayer clip={clip} muted={track.muted === true} />
                )}
              </Sequence>
            ))
          : null,
      )}
      <Captions props={props} />
      {props.musicUrl && <Music props={props} total={total} />}
      {fade > 0 && <AbsoluteFill style={{ backgroundColor: "#000", opacity: fade }} />}
    </AbsoluteFill>
  );
}

function MainPiece({ props, piece, width, height }: { props: PromoProps; piece: Piece; width: number; height: number }) {
  const frame = useCurrentFrame();
  const layout = clipLayout(props.layout, piece.clip);
  const band = bandBox(layout, width, height);
  const effect = props.imageEffects[piece.index];
  if (isLogoEffect(effect) && piece.clip.url) return <LogoCard effect={effect!} url={piece.clip.url} layout={layout} width={width} height={height} durF={piece.durF} />;
  const pos = props.imagePositions[piece.index] ?? { x: 0, y: 0 };
  const transform = effectTransform(props.imageEffects[piece.index] ?? "none", props.imageEffectSpeeds[piece.index] ?? 1, frame, piece.durF);
  const media: CSSProperties = { width: "100%", height: "100%", objectFit: "cover", objectPosition: `${50 + pos.x / 2}% ${50 + pos.y / 2}%`, transform, transformOrigin: "center center" };
  const volume = props.clipVolumes[piece.index] ?? 0;
  const text = clipText(props, piece.index);
  const url = piece.clip.url;
  return (
    <AbsoluteFill>
      <div style={{ position: "absolute", left: 0, top: band.top, width, height: band.height, overflow: "hidden" }}>
        {props.hideMainVideo || !url ? null : piece.clip.type === "video" ? (
          <OffthreadVideo src={url} trimBefore={piece.srcFrom} volume={volume} muted={volume === 0} style={media} />
        ) : (
          <Img src={url} style={media} />
        )}
      </div>
      {text.trim() && <TextClipLayer text={text} layout={layout} width={width} height={height} />}
      {layout.showWatermark && layout.watermarkText && piece.clip.type === "video" && (
        <div style={{ position: "absolute", right: 44, top: band.full ? height - 260 : band.bottom + 70 }}>
          <RichText text={layout.watermarkText} layout={{ ...layout, fontSize: 40, fontWeight: 600, textColor: layout.accentColor }} inline />
        </div>
      )}
    </AbsoluteFill>
  );
}

/**
 * The animated end card (imageEffects "logo-…"), in the band like any clip:
 * - shake: cuts in sharp, then a ~1 s camera shake with motion blur, then holds;
 * - pop: pops in with overshoot and tilt, an accent glow and one light sweep;
 * - zoom: a slow push in.
 * All three then dim slowly to about half (the reference videos' ending).
 */
function LogoCard({ effect, url, layout, width, height, durF }: { effect: string; url: string; layout: Layout; width: number; height: number; durF: number }) {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const band = bandBox(layout, width, height);
  const dim = interpolate(frame, [Math.min(durF * 0.35, durF - 1), durF], [0, 0.5], clamp);
  let transform = "";
  let filter: string | undefined;
  let opacity = 1;
  let radius = 0;
  let glow = 0;
  let shine: number | null = null;
  if (effect === LOGO_ANIMATIONS.shake) {
    const s0 = 4;
    const s1 = s0 + Math.round(fps * 1.1);
    const on = frame >= s0 && frame < s1;
    const decay = on ? interpolate(frame, [s0, s1], [1, 0.35], clamp) : 0;
    const x = on ? 22 * decay * Math.sin(frame * 1.9) : 0;
    const y = on ? 12 * decay * Math.cos(frame * 2.7) : 0;
    transform = `translate(${x.toFixed(1)}px, ${y.toFixed(1)}px) scale(${on ? 1.035 : 1})`;
    filter = on ? `blur(${interpolate(frame, [s0, s0 + 2, s1 - 3, s1], [2, 7, 6, 0], clamp).toFixed(1)}px)` : undefined;
  } else if (effect === LOGO_ANIMATIONS.pop) {
    const pop = spring({ frame, fps, config: { damping: 11, stiffness: 140, mass: 0.7 } });
    transform = `scale(${interpolate(pop, [0, 1], [0.5, 0.88]) * interpolate(frame, [0, durF], [1, 1.04], clamp)}) rotate(${interpolate(pop, [0, 1], [-5, 0])}deg)`;
    opacity = interpolate(frame, [0, 6], [0, 1], clamp);
    radius = 44;
    glow = interpolate(frame, [0, 12, 30], [0, 0.75, 0.4], clamp);
    shine = interpolate(frame, [10, 34], [-40, 140], clamp);
  } else {
    transform = `scale(${interpolate(frame, [0, durF], [1, 1.12], clamp)})`;
  }
  return (
    <AbsoluteFill>
      <div
        style={{
          position: "absolute",
          left: 0,
          top: band.top,
          width,
          height: band.height,
          opacity,
          transform,
          filter,
          borderRadius: radius,
          overflow: "hidden",
          boxShadow: glow ? `0 0 ${Math.round(160 * glow)}px ${Math.round(40 * glow)}px ${withAlpha(layout.accentColor, glow)}` : undefined,
        }}
      >
        <Img src={url} style={{ width: "100%", height: "100%", objectFit: "cover" }} />
        {shine !== null && <div style={{ position: "absolute", inset: 0, background: `linear-gradient(105deg, transparent ${shine - 18}%, rgba(255,255,255,0.38) ${shine}%, transparent ${shine + 18}%)` }} />}
      </div>
      {dim > 0 && <AbsoluteFill style={{ backgroundColor: "#000", opacity: dim }} />}
    </AbsoluteFill>
  );
}

/** "#ff6b00", 0.4 → "rgba(255,107,0,0.4)" */
export function withAlpha(hex: string, a: number) {
  const n = parseInt(hex.slice(1), 16);
  return `rgba(${(n >> 16) & 255},${(n >> 8) & 255},${n & 255},${a.toFixed(3)})`;
}

const withTextColor = (layout: Layout, color: string | undefined): Layout => (color ? { ...layout, textColor: color } : layout);

/** The CTA sits where the clip under it puts text: above a band, or near the top of a phone recording that fills the frame. */
function ctaLayout(props: PromoProps, pieces: Piece[], startFrame: number): Layout {
  const under = pieces.find((p) => startFrame >= p.from && startFrame < p.from + p.durF);
  return under ? clipLayout(props.layout, under.clip) : props.layout;
}

/**
 * Text above the band (on top of the clip when it fills the frame): a clip's own text or a text clip.
 * `y` (a text clip's textY) puts the text's middle at that fraction of the height instead, over the video.
 */
function TextClipLayer({ text, layout, width, height, y, bg }: { text: string; layout: Layout; width: number; height: number; y?: number; bg?: string }) {
  if (!text.trim()) return null;
  const band = bandBox(layout, width, height);
  const place: CSSProperties = y !== undefined ? { top: Math.round(height * y), transform: "translateY(-50%)" } : band.full ? { top: Math.round(height * 0.12) } : { bottom: height - band.top + layout.textGap };
  return (
    <div style={{ position: "absolute", left: 0, width, padding: "0 28px", boxSizing: "border-box", display: "flex", justifyContent: "center", ...place }}>
      <RichText text={text} layout={layout} shadow={!bg && (band.full || y !== undefined)} bg={bg} />
    </div>
  );
}

/** `bg` (a CSS color) draws a rounded box behind each line, TikTok-style. */
export function RichText({ text, layout, shadow = false, inline = false, bg }: { text: string; layout: Layout; shadow?: boolean; inline?: boolean; bg?: string }) {
  const css: CSSProperties = {
    fontFamily: `${layout.fontFamily}, 'Helvetica Neue', Arial, sans-serif`,
    fontSize: layout.fontSize,
    fontWeight: layout.fontWeight,
    color: layout.textColor,
    lineHeight: 1.18,
    textAlign: "center",
    letterSpacing: -0.3,
    whiteSpace: "pre-wrap",
    textShadow: shadow ? "0 4px 18px rgba(0,0,0,0.85)" : undefined,
  };
  const parts = parseAccent(text).map((p, i) => (p.accent ? <span key={i} style={{ color: layout.accentColor, fontWeight: Math.max(layout.fontWeight, 600) }}>{p.text}</span> : <span key={i}>{p.text}</span>));
  if (bg) {
    // One inline box that breaks with the text, so every line gets its own padded, rounded box.
    const box: CSSProperties = { background: bg, padding: "0.06em 0.32em", borderRadius: "0.22em", boxDecorationBreak: "clone", WebkitBoxDecorationBreak: "clone" };
    return (
      <div style={{ ...css, lineHeight: 1.42 }}>
        <span style={box}>{parts}</span>
      </div>
    );
  }
  return inline ? <span style={css}>{parts}</span> : <div style={css}>{parts}</div>;
}

/** Shortshero's caption drawing: words in batches, the spoken one highlighted. */
function Captions({ props }: { props: PromoProps }) {
  const frame = useCurrentFrame();
  const style = toRenderStyle(props.captionStyle as Record<string, unknown> | null | undefined);
  if (style.disabled || props.captions.length === 0) return null;
  const nowMs = (frame / FPS) * 1000;
  const size = style.wordsPerBatch || 3;
  let group: PromoProps["captions"] | null = null;
  for (let i = 0; i < props.captions.length; i += size) {
    const chunk = props.captions.slice(i, i + size);
    if (nowMs >= chunk[0].start && nowMs <= chunk[chunk.length - 1].end) {
      group = chunk;
      break;
    }
  }
  if (!group) return null;
  return (
    <AbsoluteFill>
      <div style={captionGroupStyle(style)}>
        {group.map((w, i) => (
          <span key={i} style={captionWordStyle(style, nowMs >= w.start && nowMs <= w.end)}>{w.text}</span>
        ))}
      </div>
    </AbsoluteFill>
  );
}

function Music({ props, total }: { props: PromoProps; total: number }) {
  const fadeFrames = Math.round(props.musicFadeOutSec * FPS);
  return (
    <Audio
      src={props.musicUrl}
      trimBefore={Math.round(props.musicStartSec * FPS)}
      volume={(f) => props.musicVolume * interpolate(f, [0, 6, Math.max(7, total - fadeFrames), total], [0, 1, 1, 0], clamp)}
    />
  );
}

/** Shortshero's effect ids (ImageEffectsPanel), as a CSS transform. */
export function effectTransform(effect: string, speed: number, frame: number, N: number): string {
  const EN = Math.max(1, N / Math.max(0.1, speed));
  const SLIDE = Math.max(1, (N * 0.6) / Math.max(0.1, speed));
  const at = (a: number, b: number, end = EN) => interpolate(frame, [0, end], [a, b], clamp);
  switch (effect) {
    case "zoom-in": return `scale(${at(1, 1.2)})`;
    case "zoom-out": return `scale(${at(1.2, 1)})`;
    case "scroll-left": return `scale(1.1) translateX(${at(5, -5)}%)`;
    case "scroll-right": return `scale(1.1) translateX(${at(-5, 5)}%)`;
    case "scroll-up": return `scale(1.1) translateY(${at(5, -5)}%)`;
    case "scroll-down": return `scale(1.1) translateY(${at(-5, 5)}%)`;
    case "ken-burns-up": return `scale(${at(1, 1.08)}) translateY(${at(0, -3)}%)`;
    case "ken-burns-down": return `scale(${at(1, 1.08)}) translateY(${at(0, 3)}%)`;
    case "diagonal-up-left": return `scale(1.1) translate(${at(2, -2)}%, ${at(2, -2)}%)`;
    case "diagonal-up-right": return `scale(1.1) translate(${at(-2, 2)}%, ${at(2, -2)}%)`;
    case "diagonal-down-left": return `scale(1.1) translate(${at(2, -2)}%, ${at(-2, 2)}%)`;
    case "diagonal-down-right": return `scale(1.1) translate(${at(-2, 2)}%, ${at(-2, 2)}%)`;
    case "slide-in-left": return `translateX(${at(-100, 0, SLIDE)}%)`;
    case "slide-in-right": return `translateX(${at(100, 0, SLIDE)}%)`;
    case "slide-in-top": return `translateY(${at(-100, 0, SLIDE)}%)`;
    case "slide-in-bottom": return `translateY(${at(100, 0, SLIDE)}%)`;
    default: return "";
  }
}

type OverlayClip = PromoProps["extraTracks"][number]["clips"][number];

/** Shortshero's ExtraClipLayer (overlay tracks), plus audio clips actually playing. */
function ExtraClipLayer({ clip, muted }: { clip: OverlayClip; muted: boolean }) {
  const frame = useCurrentFrame();
  if (!clip.url?.startsWith("http")) return null;
  if (clip.type === "audio") return muted ? null : <Audio src={clip.url} trimBefore={Math.max(0, Math.round(clip.sourceStartFrame ?? 0))} volume={clip.volume ?? 1} />;
  const N = Math.max(1, clip.durationFrames ?? 30);
  const transform = effectTransform(clip.effect || "none", clip.effectSpeed ?? 1, frame, N);
  const scale = clip.overlayScale ?? 1;
  const box: CSSProperties =
    scale < 0.999
      ? { position: "absolute", width: `${scale * 100}%`, height: `${scale * 100}%`, top: "50%", left: "50%", transform: `translate(calc(-50% + ${clip.overlayX ?? 0}%), calc(-50% + ${clip.overlayY ?? 0}%))`, overflow: "hidden" }
      : { position: "absolute", inset: 0, overflow: "hidden" };
  const media: CSSProperties = { width: "100%", height: "100%", objectFit: "cover", display: "block", transform, transformOrigin: "center center" };
  return (
    <div style={box}>
      {clip.type === "video" ? (
        <OffthreadVideo src={clip.url} trimBefore={Math.max(0, Math.round(clip.sourceStartFrame ?? 0))} muted style={{ ...media, position: "absolute", inset: 0 }} />
      ) : (
        <Img src={clip.url} style={media} />
      )}
    </div>
  );
}
