// GENERATED by Automation/scripts/sync-worker.mjs from Automation/remotion/. Edit it there, then run `pnpm sync:worker`.
/**
 * Worker registration. `pnpm sync:worker` copies this folder to
 * render-hetzner/src/automation/, and render-hetzner/src/remotion-entry.tsx renders
 * <AutomationCompositions /> next to the other apps' compositions.
 */
import { Composition } from "remotion";
import { PromoVideo } from "./PromoVideo";
import { COMPOSITION_ID, DIMENSIONS, FPS, HEIGHT, WIDTH, promoPropsSchema, totalFrames, type PromoProps } from "./schema";

const PLACEHOLDER: PromoProps = promoPropsSchema.parse({
  schemaVersion: 3,
  clipList: [{ url: "https://example.com/clip.mp4", type: "video" }],
  clipDurations: [5],
  videoScript: [{ imagePrompt: "Hook", contentText: "Preview hook" }],
});

export function AutomationCompositions() {
  return (
    <Composition
      id={COMPOSITION_ID}
      component={PromoVideo}
      fps={FPS}
      width={WIDTH}
      height={HEIGHT}
      durationInFrames={totalFrames(PLACEHOLDER)}
      defaultProps={PLACEHOLDER}
      calculateMetadata={({ props }) => {
        const parsed = promoPropsSchema.parse(props);
        const { width, height } = DIMENSIONS[parsed.aspectRatio];
        return { durationInFrames: totalFrames(parsed), width, height, props: parsed };
      }}
    />
  );
}
