// GENERATED by Automation/scripts/sync-worker.mjs from Automation/remotion/. Edit it there, then run `pnpm sync:worker`.
import { useLayoutEffect, useState, type RefObject } from "react";

import { ALL_ZONE, type Zone } from "./zones";

export { ALL_ZONE, PLATFORM_ZONES, isVertical, type Zone } from "./zones";

/** Layout size of an element (frame pixels even inside a scaled-down player), kept current as it rewraps or a font loads. */
function useSize(ref: RefObject<HTMLElement | null>) {
  const [size, setSize] = useState({ w: 0, h: 0 });
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const measure = () => setSize((s) => (s.w === el.offsetWidth && s.h === el.offsetHeight ? s : { w: el.offsetWidth, h: el.offsetHeight }));
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, [ref]);
  return size;
}

/**
 * Keeps a text block inside the safe zone of a `width`×`height` frame: it wraps between the side
 * margins (and left of the like/comment rail once it reaches down there) and slides up or down
 * just enough to stay clear of the top bar and the caption area.
 * `wantTop(h)` = where the block's top would go, given its height. Returns its top and side padding in px.
 */
export function useSafeText(ref: RefObject<HTMLElement | null>, width: number, height: number, wantTop: (h: number) => number, zone: Zone = ALL_ZONE) {
  // Re-measured when it rewraps (new text, font finished loading, rail padding on or off).
  const { h } = useSize(ref);

  const minTop = zone.top * height;
  const maxTop = height - zone.bottom * height - h;
  // Taller than the whole clear area: pin to its top so the start of the hook stays readable.
  const top = Math.max(minTop, Math.min(wantTop(h), maxTop));
  const side = zone.side * width;
  const reachesRail = top + h > zone.railFrom * height;
  return { top, padLeft: side, padRight: reachesRail ? zone.railWidth * width : side, height: h };
}

/**
 * Keeps a small box that doesn't wrap (the watermark) inside the safe zone: `want(w, h)` = where its
 * top-left would go, given its size; it's slid the least distance needed to clear the bars and the like/comment rail.
 */
export function useSafeBox(ref: RefObject<HTMLElement | null>, width: number, height: number, want: (w: number, h: number) => { left: number; top: number }, zone: Zone = ALL_ZONE) {
  const { w, h } = useSize(ref);
  const p = want(w, h);
  const top = Math.max(zone.top * height, Math.min(p.top, height - zone.bottom * height - h));
  const reachesRail = top + h > zone.railFrom * height;
  const maxLeft = width - (reachesRail ? zone.railWidth : zone.side) * width - w;
  const left = Math.max(zone.side * width, Math.min(p.left, maxLeft));
  return { left, top };
}
