// GENERATED by Automation/scripts/sync-worker.mjs from Automation/remotion/. Edit it there, then run `pnpm sync:worker`.
import { useLayoutEffect, useState, type RefObject } from "react";

/**
 * Where each app draws its own buttons and text over an organic (non-ad) 9:16 post, as fractions
 * of the frame (1080×1920). The apps only publish safe zones for ads, which carry an extra CTA bar
 * and need far more room; these are the measured organic numbers (xyla.ai/tools/social-media-sizes,
 * ignitesocialmedia.com, checked 2026-10-07), with the rail starting where TikTok's ad template puts it (840px).
 * They shift a little by device and app version.
 * - top: the "Following / For you" / search bar
 * - bottom: username, caption, sound and the nav bar
 * - side: the thin edge some phones crop
 * - rail: the like / comment / share column on the right, from `railFrom` down to the caption area
 */
export interface Zone {
  top: number;
  bottom: number;
  side: number;
  railWidth: number;
  railFrom: number;
}

export const PLATFORM_ZONES = {
  // top 130 · bottom 484 · rail 140
  tiktok: { top: 0.068, bottom: 0.252, side: 0.055, railWidth: 0.13, railFrom: 0.44 },
  // top 110 · bottom 420 · rail 140
  youtube: { top: 0.057, bottom: 0.219, side: 0.055, railWidth: 0.13, railFrom: 0.45 },
  // top 220 · bottom 430 · rail 130
  instagram: { top: 0.115, bottom: 0.224, side: 0.055, railWidth: 0.12, railFrom: 0.5 },
  // Facebook Reels draws the same overlay as Instagram Reels.
  facebook: { top: 0.115, bottom: 0.224, side: 0.055, railWidth: 0.12, railFrom: 0.5 },
} satisfies Record<string, Zone>;

const zones = Object.values(PLATFORM_ZONES);
/** Clear of every app's buttons at once: text inside it shows in full on all of them. Videos keep their text in here. */
export const ALL_ZONE: Zone = {
  top: Math.max(...zones.map((z) => z.top)),
  bottom: Math.max(...zones.map((z) => z.bottom)),
  side: Math.max(...zones.map((z) => z.side)),
  railWidth: Math.max(...zones.map((z) => z.railWidth)),
  railFrom: Math.min(...zones.map((z) => z.railFrom)),
};

/** Only a vertical video has the apps' buttons drawn over it. */
export const isVertical = (width: number, height: number) => Math.abs(width / height - 9 / 16) < 0.01;

/** Layout size of an element (frame pixels even inside a scaled-down player), kept current as it rewraps or a font loads. */
function useSize(ref: RefObject<HTMLElement | null>) {
  const [size, setSize] = useState({ w: 0, h: 0 });
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const measure = () => setSize((s) => (s.w === el.offsetWidth && s.h === el.offsetHeight ? s : { w: el.offsetWidth, h: el.offsetHeight }));
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, [ref]);
  return size;
}

/**
 * Keeps a text block inside the safe zone of a `width`×`height` frame: it wraps between the side
 * margins (and left of the like/comment rail once it reaches down there) and slides up or down
 * just enough to stay clear of the top bar and the caption area.
 * `wantTop(h)` = where the block's top would go, given its height. Returns its top and side padding in px.
 */
export function useSafeText(ref: RefObject<HTMLElement | null>, width: number, height: number, wantTop: (h: number) => number, zone: Zone = ALL_ZONE) {
  // Re-measured when it rewraps (new text, font finished loading, rail padding on or off).
  const { h } = useSize(ref);

  const minTop = zone.top * height;
  const maxTop = height - zone.bottom * height - h;
  // Taller than the whole clear area: pin to its top so the start of the hook stays readable.
  const top = Math.max(minTop, Math.min(wantTop(h), maxTop));
  const side = zone.side * width;
  const reachesRail = top + h > zone.railFrom * height;
  return { top, padLeft: side, padRight: reachesRail ? zone.railWidth * width : side, height: h };
}

/**
 * Keeps a small box that doesn't wrap (the watermark) inside the safe zone: `want(w, h)` = where its
 * top-left would go, given its size; it's slid the least distance needed to clear the bars and the like/comment rail.
 */
export function useSafeBox(ref: RefObject<HTMLElement | null>, width: number, height: number, want: (w: number, h: number) => { left: number; top: number }, zone: Zone = ALL_ZONE) {
  const { w, h } = useSize(ref);
  const p = want(w, h);
  const top = Math.max(zone.top * height, Math.min(p.top, height - zone.bottom * height - h));
  const reachesRail = top + h > zone.railFrom * height;
  const maxLeft = width - (reachesRail ? zone.railWidth : zone.side) * width - w;
  const left = Math.max(zone.side * width, Math.min(p.left, maxLeft));
  return { left, top };
}
