// GENERATED by Automation/scripts/sync-worker.mjs from Automation/remotion/. Edit it there, then run `pnpm sync:worker`.
import { z } from "zod";

/**
 * Props for the one promo composition, `mcp-promo`. Shared by the dashboard
 * (the shortshero editor, previews, templates) and the render worker, so a
 * change here must be copied to BOTH: `pnpm sync:worker` copies this folder into
 * render-hetzner/src/automation/ (see remotion/README.md).
 *
 * Schema 3: the props ARE the shortshero editor's document (app/editor/[videoId]
 * edits exactly these fields: clipList, clipDurations, clipSourceOffsets,
 * videoScript, imageEffects, imagePositions, captions, captionStyle,
 * extraTracks, musicUrl…), plus `layout`, this app's look: each main-track
 * clip plays in a full-width band with its text (videoScript[i].contentText)
 * above it and a brand watermark under it, like the reference videos.
 *
 * A new video's timeline is: [AI clip] → [screen recording + CTA] → [logo
 * image], the hook as a text clip on Track 2 over the AI clip (so it can be
 * moved and resized on its own), music from its best part (lib/promo/build.ts).
 *
 * Plain zod + core `remotion` only: the worker runs remotion 4.0.459 and zod 4.3.
 */
export const SCHEMA_VERSION = 3;
export const COMPOSITION_ID = "mcp-promo";

export const FPS = 30;
export const WIDTH = 1080;
export const HEIGHT = 1920;

export const ASPECT_RATIOS = ["9:16", "16:9", "1:1", "4:5"] as const;
export type DocAspectRatio = (typeof ASPECT_RATIOS)[number];
export const DIMENSIONS: Record<DocAspectRatio, { width: number; height: number }> = {
  "9:16": { width: 1080, height: 1920 },
  "16:9": { width: 1920, height: 1080 },
  "1:1": { width: 1080, height: 1080 },
  "4:5": { width: 1080, height: 1350 },
};

/** The logo the end card uses until a template picks another one. */
export const DEFAULT_LOGO_URL = "https://pub-17d3bc8310254f6eb92f3cff6a0c5119.r2.dev/logo/7578bf99-logo-website.png";
export const DEFAULT_CTA = "Automate Content Creation with\n*ShortsHero.com*";

const hex = z.string().regex(/^#[0-9a-fA-F]{6}$/, "hex color like #ffffff");

/** "full" = the clip fills the frame and the text sits on top of it. */
export const MEDIA_ASPECTS = ["16:9", "4:5", "1:1", "9:16", "full"] as const;
export type MediaAspect = (typeof MEDIA_ASPECTS)[number];
export const FONTS = ["Montserrat", "Inter", "Poppins", "Anton", "Bebas Neue", "Arial", "Georgia"] as const;

/** This app's look. A template stores it; the editor's Style panel changes it per video. */
export const layoutSchema = z.object({
  fontFamily: z.enum(FONTS).catch("Montserrat").default("Montserrat"),
  fontWeight: z.number().int().min(300).max(900).catch(500).default(500),
  fontSize: z.number().min(24).max(160).catch(76).default(76),
  textColor: hex.catch("#ffffff").default("#ffffff"),
  /** Words wrapped in *stars* are drawn in this color ("…with *ShortsHero.com*"). */
  accentColor: hex.catch("#ff6b00").default("#ff6b00"),
  bgColor: hex.catch("#000000").default("#000000"),
  /** Shape of the band every main-track clip plays in. */
  mediaAspect: z.enum(MEDIA_ASPECTS).catch("16:9").default("16:9"),
  /** Pixels between the bottom of the text and the top of the band. */
  textGap: z.number().min(0).max(400).catch(56).default(56),
  watermarkText: z.string().max(40).catch("ShortsHero.com").default("ShortsHero.com"),
  showWatermark: z.boolean().catch(true).default(true),
  /** Fade the last clip (the logo) to black over its final 0.6 s. */
  fadeOutEnd: z.boolean().catch(true).default(true),
});
export type Layout = z.infer<typeof layoutSchema>;
/** Kept as an alias: templates call their look "style". */
export type StyleProps = Layout;
export const styleSchema = layoutSchema;
export const DEFAULT_LAYOUT: Layout = layoutSchema.parse({});
export const DEFAULT_STYLE = DEFAULT_LAYOUT;

export const mainClipSchema = z.object({
  url: z.string(),
  type: z.enum(["video", "photo"]),
  thumbnail: z.string().optional(),
  query: z.string().optional(),
  /** This clip's own band shape (the hook clip plays full-screen 9:16). Absent = layout.mediaAspect. */
  mediaAspect: z.enum(MEDIA_ASPECTS).optional(),
});
export type MainClip = z.infer<typeof mainClipSchema>;

const scriptItemSchema = z
  .object({ imagePrompt: z.string().default(""), contentText: z.string().optional(), ContentText: z.string().optional() })
  .passthrough();

export const captionWordSchema = z.object({ text: z.string(), start: z.number(), end: z.number() });

/**
 * An overlay clip on an extra track (shortshero's ExtraClip). Loose on purpose: the editor adds fields.
 * type "text" (this app's addition) draws `text` where a clip's text goes, above the band;
 * `role: "hook"` marks the video's hook.
 */
export const extraClipSchema = z
  .object({
    id: z.string(),
    url: z.string().default(""),
    type: z.enum(["image", "video", "audio", "text"]),
    text: z.string().optional(),
    role: z.string().optional(),
    /** Text clips: where the text's middle sits, as a fraction of the frame height (0 top, 1 bottom). Absent = above the band. */
    textY: z.number().min(0).max(1).optional(),
    /** Text clips: kept on the timeline (and its text kept) but not drawn. */
    hidden: z.boolean().optional(),
    /** Text clips: a box behind each line of text, in this color ("#000000") at textBgOpacity (default 1). Absent = no box. */
    textBg: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
    textBgOpacity: z.number().min(0).max(1).optional(),
    name: z.string().default(""),
    startFrame: z.number(),
    durationFrames: z.number(),
    sourceStartFrame: z.number().optional(),
    volume: z.number().optional(),
    effect: z.string().optional(),
    effectSpeed: z.number().optional(),
    overlayX: z.number().optional(),
    overlayY: z.number().optional(),
    overlayScale: z.number().optional(),
    thumbnail: z.string().optional(),
  })
  .passthrough();
export const extraTrackSchema = z
  .object({ id: z.string(), label: z.string().default(""), clips: z.array(extraClipSchema).default([]), locked: z.boolean().optional(), visible: z.boolean().optional(), muted: z.boolean().optional() })
  .passthrough();

export const promoPropsSchema = z.object({
  schemaVersion: z.literal(SCHEMA_VERSION),
  aspectRatio: z.enum(ASPECT_RATIOS).catch("9:16").default("9:16"),
  layout: layoutSchema.default(DEFAULT_LAYOUT),
  /** The main track, in order. */
  clipList: z.array(mainClipSchema).min(1),
  /** Seconds each main-track clip plays. */
  clipDurations: z.array(z.number().min(0.05).max(3600)),
  /** Where each clip starts inside its own file, in seconds (trim / split). */
  clipSourceOffsets: z.array(z.number().min(0)).default([]),
  /** The main-track clips' own sound, 0-1. 0 (music only) when absent. */
  clipVolumes: z.array(z.number().min(0).max(1)).default([]),
  /** videoScript[i].contentText is the text above clip i (hook, CTA…). */
  videoScript: z.array(scriptItemSchema).default([]),
  imageEffects: z.array(z.string()).default([]),
  imageEffectSpeeds: z.array(z.number()).default([]),
  imagePositions: z.array(z.object({ x: z.number(), y: z.number() })).default([]),
  /** Word captions, timeline milliseconds. */
  captions: z.array(captionWordSchema).default([]),
  /** The editor's CaptionStyle (app/editor/[videoId]/editor-utils.ts). */
  captionStyle: z.record(z.string(), z.unknown()).nullish(),
  extraTracks: z.array(extraTrackSchema).default([]),
  musicUrl: z.string().default(""),
  musicVolume: z.number().min(0).max(1).default(0.8),
  /** Where in the song the video starts: its best part (lib/promo/music.ts). */
  musicStartSec: z.number().min(0).default(0),
  musicFadeOutSec: z.number().min(0).max(10).default(1.5),
  hideMainVideo: z.boolean().default(false),
  /** Editor-only state, stored with the video so the editor reopens the same way. Not rendered. */
  mediaLibrary: z.array(z.unknown()).optional(),
  editorState: z.record(z.string(), z.unknown()).optional(),
});
export type PromoProps = z.infer<typeof promoPropsSchema>;
export type PromoPropsInput = z.input<typeof promoPropsSchema>;

export const toFrames = (s: number) => Math.max(0, Math.round(s * FPS));

export interface Piece {
  index: number;
  from: number;
  durF: number;
  clip: MainClip;
  /** Frame inside the clip's own file this piece starts at. */
  srcFrom: number;
}

/** The main track laid end to end. Same maths as the editor's buildClips (no padding). */
export function mainPieces(p: Pick<PromoProps, "clipList" | "clipDurations" | "clipSourceOffsets">): Piece[] {
  let from = 0;
  return p.clipList.map((clip, index) => {
    const durF = Math.max(1, toFrames(p.clipDurations[index] ?? 3));
    const piece = { index, from, durF, clip, srcFrom: toFrames(p.clipSourceOffsets[index] ?? 0) };
    from += durF;
    return piece;
  });
}

/** Total length: the main track, or the last overlay clip if it runs longer. */
export function totalFrames(p: Pick<PromoProps, "clipList" | "clipDurations" | "clipSourceOffsets" | "extraTracks">): number {
  const pieces = mainPieces(p);
  const last = pieces[pieces.length - 1];
  let end = last ? last.from + last.durF : 1;
  for (const t of p.extraTracks ?? []) for (const c of t.clips ?? []) end = Math.max(end, Math.round(c.startFrame + c.durationFrames));
  return Math.max(1, end);
}

export const totalSeconds = (p: PromoProps) => totalFrames(p) / FPS;

export function aspectRatio(a: Exclude<MediaAspect, "full">): number {
  const [w, h] = a.split(":").map(Number);
  return w / h;
}

/** The layout a main-track clip plays in: its own band shape when it has one. */
export const clipLayout = (layout: Layout, clip: Pick<MainClip, "mediaAspect">): Layout => (clip.mediaAspect ? { ...layout, mediaAspect: clip.mediaAspect } : layout);

/** Where the media band sits in a frame of this size: full width, vertically centred. */
export function bandBox(layout: Pick<Layout, "mediaAspect">, width = WIDTH, height = HEIGHT) {
  if (layout.mediaAspect === "full") return { top: 0, height, bottom: height, full: true };
  const h = Math.min(height, Math.round(width / aspectRatio(layout.mediaAspect)));
  const top = Math.round((height - h) / 2);
  return { top, height: h, bottom: top + h, full: h >= height * 0.8 };
}

/** "Try *this*" → [{text:"Try ",accent:false},{text:"this",accent:true}] */
export function parseAccent(text: string): { text: string; accent: boolean }[] {
  return text.split(/(\*[^*]+\*)/g).filter(Boolean).map((part) => (part.startsWith("*") && part.endsWith("*") && part.length > 2 ? { text: part.slice(1, -1), accent: true } : { text: part, accent: false }));
}

/** The text above a main-track clip. */
export const clipText = (p: Pick<PromoProps, "videoScript">, i: number) => {
  const s = p.videoScript[i];
  return (s?.contentText ?? s?.ContentText ?? "") as string;
};

export const HOOK_TRACK_ID = "track-2";
/** The end card's animations (template "logoAnimation" → imageEffects id, drawn by PromoVideo's LogoCard). */
export const LOGO_ANIMATIONS = { shake: "logo-shake", pop: "logo-pop", zoom: "logo-zoom" } as const;
export type LogoAnimation = keyof typeof LOGO_ANIMATIONS | "none";
const LOGO_EFFECT_IDS: string[] = Object.values(LOGO_ANIMATIONS);
export const isLogoEffect = (id: string | undefined) => !!id && LOGO_EFFECT_IDS.includes(id);
export type ExtraClip = z.infer<typeof extraClipSchema>;

/** The hook's text clip, wherever it was dragged to. */
export function hookClip(p: Pick<PromoProps, "extraTracks">): ExtraClip | null {
  for (const t of p.extraTracks ?? []) for (const c of t.clips ?? []) if (c.type === "text" && c.role === "hook") return c;
  return null;
}

/**
 * Moves the hook off clip 1 (videoScript[0]) onto its own text clip on Track 2,
 * covering clip 1 exactly, so the video looks the same. Videos made before text
 * clips existed get this when they're next opened or edited. No-op when there's
 * already a hook clip or no hook text.
 */
export function withHookClip<T extends Pick<PromoProps, "extraTracks" | "videoScript" | "clipList" | "clipDurations" | "clipSourceOffsets">>(p: T): T {
  const text = clipText(p, 0);
  if (hookClip(p) || !text.trim()) return p;
  const first = mainPieces(p)[0];
  const clip: ExtraClip = { id: "hook", url: "", type: "text", role: "hook", name: "Hook", text, startFrame: 0, durationFrames: first?.durF ?? FPS * 3 };
  const tracks = [...(p.extraTracks ?? [])];
  while (tracks.length < 2) tracks.push({ id: `track-${tracks.length + 1}`, label: `Track ${tracks.length + 1}`, clips: [] });
  const ti = Math.max(0, tracks.findIndex((t) => t.id === HOOK_TRACK_ID));
  tracks[ti] = { ...tracks[ti], clips: [...tracks[ti].clips, clip] };
  const videoScript = [...p.videoScript];
  videoScript[0] = { ...videoScript[0], contentText: "" };
  delete (videoScript[0] as { ContentText?: string }).ContentText;
  return { ...p, extraTracks: tracks, videoScript };
}
