// GENERATED by Automation/scripts/sync-worker.mjs from Automation/remotion/. Edit it there, then run `pnpm sync:worker`.
// No React here: the server renders TikTok slides with these numbers (lib/slideshow/draw.ts),
// and server code can't import a module that uses hooks. safeZone.ts re-exports them.

/**
 * Where each app draws its own buttons and text over an organic (non-ad) 9:16 post, as fractions
 * of the frame (1080×1920). The apps only publish safe zones for ads, which carry an extra CTA bar
 * and need far more room; these are the measured organic numbers (xyla.ai/tools/social-media-sizes,
 * ignitesocialmedia.com, checked 2026-10-07), with the rail starting where TikTok's ad template puts it (840px).
 * They shift a little by device and app version.
 * - top: the "Following / For you" / search bar
 * - bottom: username, caption, sound and the nav bar
 * - side: the thin edge some phones crop
 * - rail: the like / comment / share column on the right, from `railFrom` down to the caption area
 */
export interface Zone {
  top: number;
  bottom: number;
  side: number;
  railWidth: number;
  railFrom: number;
}

export const PLATFORM_ZONES = {
  // top 130 · bottom 484 · rail 140
  tiktok: { top: 0.068, bottom: 0.252, side: 0.055, railWidth: 0.13, railFrom: 0.44 },
  // top 110 · bottom 420 · rail 140
  youtube: { top: 0.057, bottom: 0.219, side: 0.055, railWidth: 0.13, railFrom: 0.45 },
  // top 220 · bottom 430 · rail 130
  instagram: { top: 0.115, bottom: 0.224, side: 0.055, railWidth: 0.12, railFrom: 0.5 },
  // Facebook Reels draws the same overlay as Instagram Reels.
  facebook: { top: 0.115, bottom: 0.224, side: 0.055, railWidth: 0.12, railFrom: 0.5 },
} satisfies Record<string, Zone>;

const zones = Object.values(PLATFORM_ZONES);
/** Clear of every app's buttons at once: text inside it shows in full on all of them. Videos keep their text in here. */
export const ALL_ZONE: Zone = {
  top: Math.max(...zones.map((z) => z.top)),
  bottom: Math.max(...zones.map((z) => z.bottom)),
  side: Math.max(...zones.map((z) => z.side)),
  railWidth: Math.max(...zones.map((z) => z.railWidth)),
  railFrom: Math.min(...zones.map((z) => z.railFrom)),
};

/** Only a vertical video has the apps' buttons drawn over it. */
export const isVertical = (width: number, height: number) => Math.abs(width / height - 9 / 16) < 0.01;
